declare const jspdf: any;

/**
 * A utility function that simulates a server-side API call for file processing.
 * This mock generates a plausible output file for various conversions to provide
 * a better user experience in the demo environment.
 * @param endpoint The API endpoint to simulate.
 * @param formData The FormData object containing the file.
 * @param onProgress An optional callback to report progress updates.
 * @returns A promise that resolves with the Blob and filename of the created file.
 */
export const callStirlingApi = async (
  endpoint: string,
  formData: FormData,
  onProgress?: (message: string) => void
): Promise<{ blob: Blob; filename: string }> => {
  
  onProgress?.('Initializing process...');
  await new Promise(resolve => setTimeout(resolve, 500));
  onProgress?.('Uploading file to secure server...');
  
  const file = formData.get('file') as File;
  if (!file) {
      throw new Error("No file found in the request.");
  }
  
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  onProgress?.('Processing file on server...');

  const originalName = file.name;
  const baseName = originalName.substring(0, originalName.lastIndexOf('.'));

  let blob: Blob;
  let filename: string;

  // Determine output format from endpoint
  let outputExtension = 'pdf'; // Default
  if (endpoint.includes('pdf-to-xps')) {
    outputExtension = 'xps';
  } else if (endpoint.includes('pdf-to-excel')) {
    outputExtension = 'csv';
  } else if (endpoint.includes('pdf-to-powerpoint')) {
    outputExtension = 'pptx';
  }

  filename = `${baseName}.${outputExtension}`;

  if (outputExtension === 'pdf') {
    // Generate a more realistic mock PDF for any conversion TO PDF
    const { jsPDF } = jspdf;
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text(`Simulated PDF Conversion`, 10, 20);
    doc.setFontSize(12);
    doc.text(`Original file: ${file.name}`, 10, 40);
    doc.text(`This document was generated by the LOLOPDF mock API.`, 10, 60);
    doc.text(`In a real application, this would be a high-fidelity conversion`, 10, 70);
    doc.text(`of your original document.`, 10, 80);
    blob = doc.output('blob');
  } else {
    // For non-PDF outputs, create a simple text-based file
    let outputContent = `This is a simulated ${outputExtension.toUpperCase()} file converted from ${file.name}.`;
    let outputMimeType = 'text/plain';

    if (outputExtension === 'xps') {
        outputMimeType = 'application/vnd.ms-xpsdocument';
    } else if (outputExtension === 'csv') {
        outputMimeType = 'text/csv';
        outputContent = `Header1,Header2,Header3\nValue1,Value2,Value3\nThis is simulated CSV data from ${file.name}.`;
    } else if (outputExtension === 'pptx') {
        outputMimeType = 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
    }
    blob = new Blob([outputContent], { type: outputMimeType });
  }

  onProgress?.('Finalizing conversion...');
  await new Promise(resolve => setTimeout(resolve, 1000));
  
  return { blob, filename };
};
